"""crea todas las tablas desde cero

Revision ID: 1d360758ca70
Revises: 
Create Date: 2025-06-03 14:18:13.047055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d360758ca70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barriles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barriles_id'), 'barriles', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cnpj_cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('envases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('reutilizable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envases_id'), 'envases', ['id'], unique=False)
    op.create_table('fermentadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('capacidad_litros', sa.Float(), nullable=False),
    sa.Column('estado_actual', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fermentadores_id'), 'fermentadores', ['id'], unique=False)
    op.create_table('movimientos_envases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_envases_id'), 'movimientos_envases', ['id'], unique=False)
    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('precio_litro', sa.Float(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precios_id'), 'precios', ['id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fermentador', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_embarrilado', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_fermentador'], ['fermentadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_id'), 'lotes', ['id'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('id_envase', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('mensaje_original', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_envase'], ['envases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('fecha_cobro', sa.DateTime(), nullable=True),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_table('reportes_fermentador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.Column('etapa', sa.String(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_fermentador_id'), 'reportes_fermentador', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reportes_fermentador_id'), table_name='reportes_fermentador')
    op.drop_table('reportes_fermentador')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_lotes_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_precios_id'), table_name='precios')
    op.drop_table('precios')
    op.drop_index(op.f('ix_movimientos_envases_id'), table_name='movimientos_envases')
    op.drop_table('movimientos_envases')
    op.drop_index(op.f('ix_fermentadores_id'), table_name='fermentadores')
    op.drop_table('fermentadores')
    op.drop_index(op.f('ix_envases_id'), table_name='envases')
    op.drop_table('envases')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_barriles_id'), table_name='barriles')
    op.drop_table('barriles')
    # ### end Alembic commands ###
