"""init nueva estructura de modelos

Revision ID: 3fcdf25837ce
Revises: 
Create Date: 2025-06-04 10:06:57.342367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcdf25837ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cnpj_cpf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_fermentador', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_fermentador'], ['fermentadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_id'), 'lotes', ['id'], unique=False)
    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('precio_litro', sa.Float(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precios_id'), 'precios', ['id'], unique=False)
    op.create_table('rotulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotulos_id'), 'rotulos', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=False),
    sa.Column('fecha_cobro', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('ids_barriles', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('observacion', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_table('barriles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barriles_id'), 'barriles', ['id'], unique=False)
    op.create_table('botellas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botellas_id'), 'botellas', ['id'], unique=False)
    op.create_table('registro_fermentador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=True),
    sa.Column('id_fermentador', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fermentador'], ['fermentadores.id'], ),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_fermentador_id'), 'registro_fermentador', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_fermentador_id'), table_name='registro_fermentador')
    op.drop_table('registro_fermentador')
    op.drop_index(op.f('ix_botellas_id'), table_name='botellas')
    op.drop_table('botellas')
    op.drop_index(op.f('ix_barriles_id'), table_name='barriles')
    op.drop_table('barriles')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_rotulos_id'), table_name='rotulos')
    op.drop_table('rotulos')
    op.drop_index(op.f('ix_precios_id'), table_name='precios')
    op.drop_table('precios')
    op.drop_index(op.f('ix_lotes_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
