"""crear tabla movimientos_stock

Revision ID: 95354f4e9a64
Revises: c0c5a4d2f49d
Create Date: 2025-06-03 11:18:11.572886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95354f4e9a64'
down_revision: Union[str, None] = 'c0c5a4d2f49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('volumen_litros', sa.Float(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('id_barril', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('mensaje_original', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    # ### end Alembic commands ###
